codecheftest/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^',include('home_test.urls')),
    url('^',include('tcg.urls')),
]

home_test/urls.py
from django.conf.urls import url,include
from . import views

app_name='home_test'
urlpatterns = [
    url('^$',views.home1,name="home"),
    url('^logout/$',views.logout_user,name="logout"),
    url('^myprofile/$',views.profile,name="profile"),
 	url('^cp/login_user/$',views.login_user,name="login_user"),
 	url('^cp/login/$',views.loginView,name="login"),
 	url('^testcase/gogenerate/$',views.GenerateTest.as_view(),name="GenerateTest"),
 	url('^tc/$',views.tc,name="tc"),
 	url('^home/$',views.home,name="home1"),
 	url(r'^src/OAuth2/',views.verify,name='verify'),
	url(r'^home/problemsearch/(?P<pcode>\w+)/',views.search,name='search')
]

tcg/urls.py
from django.conf.urls import url,include
from . import views
app_name='tcg'
urlpatterns = [
    url('^tcg/$',views.tcg,name="tcg1"),
    url('^tcg/numbers/$',views.number,name="numbers"),
    url('^tcg/matrix/$',views.matrixgen,name="matrix"),
    url('^tcg/array/$',views.arraygen,name="array"),
    url('^tcg/string/$',views.stringgen,name="string"),
    # url('^tcg/static/tcg/lifecoder_1/matrix.txt/$',views.abc,name="abc")


    ]

home_test/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    rating = models.CharField(max_length=50,null=True)
    rank=models.CharField(max_length=50,null=True)
    todo=models.TextField(default="",null=True)
    country=models.CharField(max_length=50,blank=True,null=True)
    points=models.CharField(max_length=10,default="",null=True)
    scope=models.TextField(default="")
    access_token=models.CharField(max_length=500,default="")
    refresh_token=models.CharField(max_length=500,default="")

    def _str_(self):
        return str(self.user)

class Tags(models.Model):
    tag_name=models.CharField(max_length=200,null=True)

class Problems(models.Model):
    prob_name=models.CharField(max_length=200)
    prob_code=models.CharField(max_length=200,null=True)
    prob_tag=models.TextField(null=True)

    def __str__(self):
        return str(self.prob_name)
        
class UserSolved(models.Model):
    user=models.ForeignKey(Profile,on_delete=models.CASCADE)
    problem=models.ForeignKey(Problems,on_delete=models.CASCADE)
    solved=models.IntegerField(default=1)
    

home_test/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from home_test.models import Profile

class FilterForm(forms.Form):
    rank_choices = (
            ("a", "1 star"),
            ("b", "2 star"),
            ("c","3 star"),
            ("d","4 star"),
            ("e","5 star")
            )
    ranks= forms.MultipleChoiceField(widget=forms.RadioSelect(),
                                         choices=rank_choices)
    
    # countr = Profile.objects.filter(solved__contains=['country'])
    # print (countr)

    # def get_my_choices():
    #     # you place some logic here
    #     countr = Profile.objects.filter(solved__contains=['country'])
    #     print (countr)
    #     return countr

    # my_choice_field = forms.ChoiceField(choices=countr)

class ProbmSearchForm(forms.Form):
    probcode=   forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Enter the problem name or code...','class':'form-control form-control-lg'}))


# class SignUpForm(UserCreationForm):
#     email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
#
#     class Meta:
#         model = User
#         fields = ('username', 'email', 'password1', 'password2', )


class UploadFileForm(forms.Form):
    
    PROGRAM = (
       ("cpp", ("C++")),
       ("py", ("Python")), 
       ("c", ("C")),
    )
    bruteforce=forms.FileField()
    brute = forms.ChoiceField(choices=PROGRAM,label="Select the programming language in which you have written brute force",required=True)
    optimize=forms.FileField()
    opti = forms.ChoiceField(choices=PROGRAM,label="Select the programming language in which you have written optimized code",required=True)
    

    def clean_opti(self):
      
      code_opti=self.cleaned_data.get("opti")		
      opti_file=self.cleaned_data.get("optimize")
      
      if ("." + code_opti) not in opti_file.name: 
        raise forms.ValidationError("Please enter write the file with write extension")
      return code_opti



    def clean_brute(self):
      code_bru=self.cleaned_data.get("brute")
      bru_file=self.cleaned_data.get("bruteforce")
      if ("." + code_bru) not in bru_file.name: 
        raise forms.ValidationError("Please enter write the file with write extension")
      return code_bru

home_test/views.py
import json
from home_test.models import Profile,Tags,Problems,UserSolved
from home_test.taskamcp import realwork
from home_test.forms import UploadFileForm,ProbmSearchForm,FilterForm
from django.contrib.auth import login,logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from home_test.alltestcases import test6,test7,test8,test9,test10,testprince,cootest
from home_test.alltestcases import sep1,sep2,sep3,sep5,sep6,sep7,sep8
import requests
from urllib.request import Request, urlopen
import os
from django.conf import settings
from django.http import HttpResponse

def login_user(request):   
    return redirect("https://api.codechef.com/oauth/authorize?response_type=code&client_id=6417f628edbda4e8b1540c569e2be415&state=xyz&redirect_uri=http://149.129.138.109:8000/src/OAuth2/")

def loginView(request):
    form = UploadFileForm()
    return render(request,'home_test/index.html',{'form':form,'name' : request.user.username})

def logout_user(request):
    logout(request)
    return redirect('/')

def home(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)

        if form.is_valid():            
            op=form.cleaned_data.get("opti")
            br=form.cleaned_data.get("brute")
            bru=request.FILES['bruteforce']
            opi=request.FILES['optimize']
            realwork(bru,opi,br,op)
            return HttpResponse("Done")
        else:
            form = UploadFileForm(request.POST, request.FILES)
            return render(request, 'home_test/index.html', {'form': form})
    else:
        form = UploadFileForm()
        return render(request, 'home_test/index.html', {'form':form,})

def tc(request):
    return render(request, 'home_test/base.html')

def home1(request):
    probform = ProbmSearchForm()
    if request.method=="POST":
        probform = ProbmSearchForm(request.POST)
        if probform.is_valid():
            pcode = probform.cleaned_data.get("probcode")
            return redirect('/home/problemsearch/'+str(pcode)+'/')
        else:
            probform =ProbmSearchForm(request.POST)
            return render(request, 'home_test/home.html', {'probform': probform})
    
    return render(request, 'home_test/home.html',{'probform':probform})

def profile(request):
    prob=Problems.objects.all() 
    prof = Profile.objects.filter(user=User.objects.get(username=request.user))
    for e in prof:
        username=e.user
        rating=e.rating
        rank=e.rank
        todo=e.todo
        country=e.country
        points=e.points
    user_solved=UserSolved.objects.filter(user=Profile.objects.get(user=request.user),solved=1).prefetch_related("problem").values_list("problem__prob_name","problem__prob_code")
    user_unsolved=UserSolved.objects.filter(user=Profile.objects.get(user=request.user),solved=0).prefetch_related("problem").values_list("problem__prob_name","problem__prob_code")
    return render(request, 'home_test/profile.html',{"username":username,"rating":rating,"rank":rank,"todo":todo,'country':country,'points':points,'solved':user_solved,'unsolved':user_unsolved,'solcount':len(user_solved)})

def search(request,pcode):
    users_solved=UserSolved.objects.filter(problem__prob_code=pcode)
    user_unsolved=UserSolved.objects.filter(user=Profile.objects.get(user=request.user),solved=0).prefetch_related("problem").values_list("problem__prob_name","problem__prob_code")
    print(users_solved)
    if users_solved.exists():
        return render(request,'home_test/usersearch.html',{"all_users":users_solved,"unsolved":user_unsolved,"pcode":pcode})
    else:
        return HttpResponse("Oops the problem code is incorrect or no users for this problem .Click <a href='/'>Here</a> to go back." )
    

    

# def tyc(request):
#     #url="https://www.codechef.com/problems/easy"
#     #url="https://www.codechef.com/problems/school"
#     #url="https://www.codechef.com/problems/medium"
#     #url="https://www.codechef.com/problems/hard/"
#     #url="https://www.codechef.com/problems/challenge/"
    
#     # req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
#     # web_byte = urlopen(req).read()
#     # html_doc = web_byte.decode('utf-8')
#     # soup = BeautifulSoup(html_doc, 'html.parser')
#     # all_content=soup.find('table',{"class":"dataTable"})
#     # #print(all_content)
#     # '''for problems in soup.find_all('b'):
#     #     print(problems.string)'''

#     # for link in all_content.find_all('a'):
        
#     #     x=str(link.get('href'))
#     #     if x.startswith('/problems'):
#     #         y=str(link.get('href'))
#     #         print(link.text)
#     #         d=(y.split('/problems/'))
#     #         Problems.objects.create(prob_name=str(link.text),prob_code=str(d[1]))



#     return render(request, 'home_test/testyourcode.html')


def verify(request):
    res=requests.post("https://api.codechef.com/oauth/token",dict({"grant_type":"authorization_code","code":request.GET['code'],"client_id":"6417f628edbda4e8b1540c569e2be415","client_secret":"b44d5c109d29ed61a41fec7fbe05900a","redirect_uri":"http://149.129.138.109:8000/src/OAuth2/"}))
    try:
        res=json.loads(res.text)
        if "result" in res:
            access_token=res.get("result").get("data").get("access_token")
            refresh_token=res.get("result").get("data").get("refresh_token")
            scope=res.get("result").get("data").get("scope")
            res_username=requests.get("https://api.codechef.com/users/me",headers={"Authorization":"Bearer "+str(access_token)})
            response=json.loads(res_username.text)
            response=response.get("result").get("data")
            print(response)
            country=response.get("content").get("country").get("name")
            rank=response.get("content").get("rankings").get("allContestRanking").get("global")
            rating=response.get("content").get("ratings").get("allContest")
            band=response.get("content").get("band")
            solved_problem=response.get("content").get("problemStats").get("solved")
            partially_solved=response.get("content").get("problemStats").get("partiallySolved")

            exists=User.objects.filter(username=response.get("content").get("username")).exists()
            if exists:
                user=User.objects.get(username=response.get("content").get("username"))
            else:
                user=User.objects.create(username=response.get("content").get("username"),first_name=response.get("content").get("fullname"))
                Profile.objects.create(access_token=access_token, refresh_token=refresh_token, scope=scope.split(" "),user=user,country=country,rank=rank,rating=rating,points=band)

            profile_obj=Profile.objects.get(user=user)
            for key in solved_problem:
                for items in solved_problem[key]:
                    try:
                        prob=Problems.objects.get(prob_code=items)
                        UserSolved.objects.get_or_create(problem=prob,user=profile_obj)
                    except Exception as e:
                        pass

            for key in partially_solved:
                for items in partially_solved[key]:
                    try:
                        prob=Problems.objects.get(prob_code=items)
                        UserSolved.objects.get_or_create(problem=prob,user=profile_obj,solved=0)
                    except Exception as e:
                        pass

            login(request,user)
            return redirect("/")
        else:
            return HttpResponse(str(res))
    except Exception as e:
        return HttpResponse("Something went wrong try again. Click <a href='/'>Here</a> to go back." )

class GenerateTest(APIView):
    def post(self,request,*args,**kwargs):
        select=request.data.get('select')
        ques_id=request.data.get("id")
        if ques_id=='sep1':
            testcase=request.data.get("testcase")
            N=request.data.get("N")
            X=request.data.get("X")
            S=request.data.get("S")
            x,y,nol=sep1.generate(int(testcase),int(N),int(X),int(S))

        if ques_id=='sep2':
            testcase=request.data.get("testcase")
            N=request.data.get("N")
            M=request.data.get("M")
            X=request.data.get("X")
            Y=request.data.get("X")
            x,y,nol=sep2.generate(int(testcase),int(N),int(M),int(X),int(Y))

        if ques_id=='sep3':
            testcase=request.data.get("testcase")   
            N=request.data.get("N")
            minv=request.data.get("minv")
            maxv=request.data.get("maxv")
            x,y,nol=sep3.generate(int(testcase),int(N),int(minv),int(maxv))

        if ques_id=='sep5':
            testcase=request.data.get("testcase")
            N=request.data.get("N")
            M=request.data.get("M")
            Q=request.data.get("Q")
            x,y,nol=sep6.generate(int(testcase),int(N),int(M),int(Q))

        if ques_id=='sep6':
            N=request.data.get("N")
            M=request.data.get("M")
            K=request.data.get("K")
            sep7.generate(int(N),int(M),int(K))

        if ques_id=='sep7':
            testcase=request.data.get("testcase")
            N=request.data.get("N")
            arrsize=request.data.get("M")
            Q=request.data.get("Q")
            x,y,nol=sep8.generate(int(testcase),int(N),int(Q),int(arrsize))

        if ques_id=='1':
            testcase=request.data.get("testcase")
            x,y,nol=test6.generate(int(testcase))
        if ques_id=='2':
            testcase=request.data.get("testcase")
            maxn=request.data.get("N")
            x,y,nol=test7.generate((int(testcase)),(int(maxn)))
        if ques_id=='3':
            testcase=request.data.get("P")
            maxn=request.data.get("S")

home_test/templates/home_test/home.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Home</title>

    <!-- Bootstrap core CSS 
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">!-->
    <link rel="stylesheet" type="text/css" href="{% static 'home_test/vendor/bootstrap/css/bootstrap.min.css' %}"/>

    <!-- Custom fonts for this template -->
    
    <link rel="stylesheet" type="text/css" href="{% static 'home_test/vendor/font-awesome/css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'home_test/vendor/simple-line-icons/css/simple-line-icons.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'home_test/css/landing-page.min.css' %}"/>


  </head>

  <body>

    <!-- Navigation -->
    {% include 'home_test/navbar.html' %}

    <!-- Masthead -->
    <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Stuck on a problem???</h1>
              <h2 class="md-4">Take help from Community</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form method="post">
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                     {% csrf_token %}
                    {% for field in probform %}
                        {{ field }}

                    {% endfor %}
                    <!--<div class="" {{ probform.as_p }}-->
                    <!--<input class="form-control form-control-lg" placeholder="Enter the problem name or code...">-->
                </div>
                <div class="col-12 col-md-3">
                    <a href="#"><button type="submit" class="btn btn-block btn-lg btn-primary">Go!</button></a>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </header>

    <!-- Icons Grid -->
    <section class="features-icons bg-light text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-screen-desktop m-auto text-primary"></i>
              </div>
              <h3>TestCase Generator</h3>
              <p class="lead mb-0">Generates your desired tasecases for your question!</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-layers m-auto text-primary"></i>
              </div>
              <h3>Find Your Testcases</h3>
              <p class="lead mb-0">Stuck on any testcase! Find your hidden testcase easily.</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-check m-auto text-primary"></i>
              </div>
              <h3>Profile</h3>
              <p class="lead mb-0">Tells your complete codechef profile. </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Image Showcases -->
    <!-- <section class="showcase">
      <div class="container-fluid p-0">
        <div class="row no-gutters">

          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-1.jpg');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <h2>TestCase Generator</h2>
            <p class="lead mb-0">When you submit any question, sometime you get wrong answers due to the some hidden testcase.Genrate your Testcases using this tool and find your hidden Testcases</p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-2.jpg');"></div>
          <div class="col-lg-6 my-auto showcase-text">
            <h2>Updated For Bootstrap 4</h2>
            <p class="lead mb-0">Newly improved, and full of great utility classes, Bootstrap 4 is leading the way in mobile responsive web development! All of the themes on Start Bootstrap are now using Bootstrap 4!</p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-3.jpg');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <h2>Easy to Use &amp; Customize</h2>
            <p class="lead mb-0">Landing Page is just HTML and CSS with a splash of SCSS for users who demand some deeper customization options. Out of the box, just add your content and images, and your new landing page will be ready to go!</p>
          </div>
        </div>
      </div>
    </section> -->

    <!-- Testimonials -->
    <!-- <section class="testimonials text-center bg-light">
      <div class="container">
        <h2 class="mb-5">What people are saying...</h2>
        <div class="row">
          <div class="col-lg-4">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="img/testimonials-1.jpg" alt="">
              <h5>Margaret E.</h5>
              <p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="img/testimonials-2.jpg" alt="">
              <h5>Fred S.</h5>
              <p class="font-weight-light mb-0">"Bootstrap is amazing. I've been using it to create lots of super nice landing pages."</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="img/testimonials-3.jpg" alt="">
              <h5>Sarah	W.</h5>
              <p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>
            </div>
          </div>
        </div>
      </div>
    </section> -->

    <!-- Call to Action -->
<!--     <section class="call-to-action text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h2 class="mb-4">Ready to get started? Sign up now!</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section> -->

    <!-- Footer -->
    <footer class="footer bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
            <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
            </ul>
            <p class="text-muted small mb-4 mb-lg-0">&copy; CPHELPER.TK. ALL RIGHTS RESERVED. | POWERED BY CODECHEF API</p>
          </div>
          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
            <ul class="list-inline mb-0">
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-facebook fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-twitter fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-instagram fa-2x fa-fw"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

home_test/templates/home_test/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home_test:home' %}">Cp Helper</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home_test:home' %}">Home <span class="sr-only">(current)</span></a>

            </li>
            <li class="nav-item">

                <a class="nav-link" href="{% url 'home_test:home1' %}">Findyourtestcases </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tcg:tcg1' %}">Testcase Generator</a>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_anonymous %}
            <li class="nav-item">
                <a href="/cp/login_user/" class="btn btn-primary">Register</a>
            </li>
            <li class="nav-item">
                <a href="/cp/login/" class="btn btn-primary">Login</a>
            </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home_test:profile' %}">{{ request.user }}</a>
            </li>
            <li class="nav-item">
                <a href="/logout/"><button type="button" class="btn btn-primary">Logout
                </button></a>
            </li>

          {% endif %}
        </ul>
    </div>
</nav>

home_test/templates/home_test/profile.html
<!DOCTYPE html>
<html>
   <head>
    <style type="text/css">
      /* Style tab links */
.tablink {
  background-color: white;
  color: black;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  font-size: 17px;
  width: 33.33%;
}

.tablink:hover {
  background-color: red;
}

/* Style the tab content (and add height:100% for full page content) */
.tabcontent {
  color: #777;
  display: none;
  padding: 100px 20px;
  height: 100%;
}

#Home {background-color: white;}
#News {background-color: white;}
#Contact {background-color: white;}

    </style>
      {% load static %}
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <title>Profile</title>
      <link rel="stylesheet" type="text/css" href="{% static 'home_test/profile.css' %}"/>
   </head>
   <body style="background-color: lightgrey;">
      {% include 'home_test/navbar.html' %}
      <!-- <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet"> -->
      <div class="container">
         <div class="card text-center" style="margin-top: 5%;margin-bottom: 5%;">
            <div class="card-header">
               Profile
            </div>
            <div class="card-body">
               <h1 class="card-title">{{ username }}</h1>
               <div class="container">
                  <div class="row justify-content-md-center">
                     <div class="col col-lg-2">
                        <h2><strong> {{ country }} </strong></h2>
                        <p><small>Country</small></p>
                     </div>
                     <div class="col-md-auto">
                        <h2><strong> {{ points }} </strong></h2>
                        <p><small>Points</small></p>
                     </div>
                  </div>
               </div>
               <div class="container">
                  <div class="row">
                     <div class="col-sm">
                        <h2><strong> {{ rank }} </strong></h2>
                        <p><small>Rank</small></p>
                     </div>
                     <div class="col-sm">
                        <h2><strong>{{ rating }}</strong></h2>
                        <p><small>Rating</small></p>
                     </div>
                     <div class="col-sm">
                        <h2><strong>{{ solcount }}</strong></h2>
                        <p><small>Solved</small></p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         
            <div class="card text-center">
  <div class="card-header">
    <button class="tablink" onclick="openPage('Home', this,'white')" id="defaultOpen">Solved</button>
<button class="tablink" onclick="openPage('News', this, 'white')" >Unsolved</button>


<div id="Home" class="tabcontent">
  <h3>Solved</h3>
{% for solved in solved %}
                     <div class="list-group">
                        <a href=https://www.codechef.com/problems/{{ solved.1 }} class="list-group-item list-group-item-action list-group-item-light">{{ solved.0 }}</a>
                     </div>
                     {% endfor %}
</div>

<div id="News" class="tabcontent">
                    <h3>Unsolved</h3>
                       {% for unsolved in unsolved %}
                     <div class="list-group">
                        <a href=https://www.codechef.com/problems/{{ unsolved.1 }} class="list-group-item list-group-item-action list-group-item-light">{{ unsolved.0 }}</a>
                     </div>
                     {% endfor %} 
</div>



</div>         
      </div>
      <script type="text/javascript">
        function openPage(pageName, elmnt, color) {
    // Hide all elements with class="tabcontent" by default */
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    // Remove the background color of all tablinks/buttons
    tablinks = document.getElementsByClassName("tablink");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].style.backgroundColor = "";
    }

    // Show the specific tab content
    document.getElementById(pageName).style.display = "block";

    // Add the specific color to the button used to open the tab content
    elmnt.style.backgroundColor = color;
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
      </script>
   </body>
</html>